version: "3.9"
services:
    postgres:
        image: postgres:14.2
        environment:
            POSTGRES_DB: "studs"
            POSTGRES_USER: "s471848"
            POSTGRES_PASSWORD: "s471848"
        ports:
            - "5432:5432"
